### ISSUE TITLE
リリースを行う

### ISSUE THREAD

**Issue by toshihr** [andgohq/insight-bitcoin-regtest#1]
- [x] アプリ準備
- [x] 公式サイトトップページの更新
- [x] What's Up?の更新
- [x] 告知メールの配信

## 告知メール原案

大変お待たせしました。
ビットコイン自動積立貯金アプリ ベータテストを再開いたします。
ベータテストに参加されている皆様におかれましてはアプリの不具合によりご不便をおかけしました。
引き続きご利用頂けますと幸いです。

## アプリ再開のお手続き方法 (全員が対象です)
皆様が登録されたスケジュールは現在無効（INACTIVE）になっております。各自で再開の手続きを行って頂きます。

1. APIキーの権限を更新（bitFlyer, Coincheck, Krakenをご利用の方）

bitbank以外の取引所をご利用の方は、今回のアップデート以降追加の権限設定が必要です。
お手数ですが、下記をご参照の上、更新をお願いします。

 APIキーおよびAPIシークレットの登録方法: [https://dca-web.andgo.co.jp/api-register-1](https://dca-web.andgo.co.jp/api-register-1)

※ 既に発行済みのAPIキーについて権限変更を行う形で問題ありません
※ 権限設定が適切でないと購入時にエラーとなり、スケジュールが無効（INACTIVE）になります

2. スケジュールを有効にする（全員が対象）

「スケジュールをACTIVEにする」を選択し、更新ボタンを押します。

<img width="493" alt="UPDATE_SCHEDULE" src="https://user-images.githubusercontent.com/6064065/151327311-cf1bc1fb-223a-40a7-869b-6f3fbd52b841.png">

再開手続きは以上となります。

アプリログインはこちら

[https://dca.andgo.co.jp/](https://dca.andgo.co.jp/)

ご不明点等などございましたら、公式サイト内のチャット欄にてお問い合せください。

公式サイト: [https://dca-web.andgo.co.jp/](https://dca-web.andgo.co.jp/)

## New features

- 対応取引所をbitFlyer, bitbank, Coincheck, Krakenに変更

### Bug fixes & improvements

- スケジュール処理の暴走対策を追加
- 購入時のメール通知にて指定金額を記載する形に修正
- 履歴詳細にて、指定金額と実際に購入に使った金額とを分けて記載
- スケジュールに関して状態ACTIVE / INACTIVE を追加

※ 安定した動作の確認がとれていない取引所のサポートを終了しました。それに伴い、未サポートの取引所に関してAPIキーの登録情報を削除させていただきました。ご了承ください。

**Comment by toshihr** [comment]
メール案、指摘ウェルカムです。ここが気になるーとかありましたらコメントくださいな

**Comment by AkaneTaguchi-AndGo** [comment]
・スケジュール処理の暴走対策を追加
がちょっと強い表現でビビります。
・スケジュールによる購入指示が繰り返される問題の対策を追加
とか、少し柔らかくできますかね？今回、当事者にならなかったユーザーもいることですし。

**Comment by toshihr** [comment]
そうですね、優しい表現にはしたいところ。

- 意図しない購入が繰り返される場合がある件に対応

でどうでしょうか

**Comment by AkaneTaguchi-AndGo** [comment]
トップページ更新し、公式サイトからログインへのリンクを有効にしました。

**Comment by AkaneTaguchi-AndGo** [comment]
@toshihr 【AndGo ビットコイン自動積立貯金】サービス再開に関するお知らせ

大変お待たせしました。
ビットコイン自動積立貯金アプリ ベータテストを再開いたします。
こちらの公式サイトの「はじめる」ボタンからベータテストをご利用ください。
-------
AndGo自動積立貯金公式サイト: https://dca-web.andgo.co.jp/

＜積立開始までの３ステップ＞

STEP1. 上記URLの「はじめる」ボタンよりAndGo自動積立貯金へアクセス

STEP2. APIキー・APIシークレットを登録して取引所と連携
※ 権限設定が適切でないと購入時にエラーとなり、スケジュールが無効（INACTIVE）になります。設定についてはこちらをご覧ください。https://dca-web.andgo.co.jp/api-register-1

STEP3. 積立スケジュール・金額の設定

アプリへのログインにはGMailアカウント、Apple IDをご利用いただけます。

アプリログインはこちら

https://dca.andgo.co.jp/

ご不明点等などございましたら、公式サイト内のチャット欄よりお問い合せください。

公式サイト: https://dca-web.andgo.co.jp/

AndGoビットコイン自動積立貯金アプリのご利用をお待ちしております。

AndGoビットコイン自動積立貯金
サポートチーム

**Comment by toshihr** [comment]
こんなかんじで今後も汎用的に使うWelcomeメール (初回SignIn時送信)との立て付けで送ってくださいな。

```
タイトル:
【AndGoビットコイン自動積立貯金】はじめかた

内容:
ようこそ、AndGoビットコイン自動積立貯金アプリへ。
このアプリでは、どの取引所で何時、いくら相当のビットコインを購入するといった積立スケジュールを管理できます。
スケジュールに沿って、ご自身の利用されている取引所でビットコインが購入されます。

＜積立開始までの３ステップ＞
STEP1. アプリを開く
アプリURL: https://dca.andgo.co.jp/

STEP2. APIキー・APIシークレットを登録して取引所と連携

STEP3. 積立スケジュール・金額を設定

詳しくはこちら: https://dca-web.andgo.co.jp/start



ご不明点等などございましたら、公式サイト内のチャット欄よりお問い合せください。

公式サイト: https://dca-web.andgo.co.jp/

AndGoビットコイン自動積立貯金アプリのご利用をお待ちしております。

AndGoビットコイン自動積立貯金
サポートチーム

```

**Comment by AkaneTaguchi-AndGo** [comment]
@toshihr 了解。
トリガー：初回サインイン
で上記Welcomeメールを送るって認識で合ってるかな？
私の力量では設定できないのでFabianにお願いするね

**Comment by AkaneTaguchi-AndGo** [comment]
@MyNameIsOka  Hi, Good morning.
Could you arrange welcome mail on SendGrid once a user signed up to Hongo App for the first time?

Sender: AndGoカスタマーサポート<tsumitate_cs@andgo.co.jp>

Subject:
【AndGoビットコイン自動積立貯金】はじめかた

Contents:
ようこそ、AndGoビットコイン自動積立貯金アプリへ。
このアプリでは、どの取引所で何時、いくら相当のビットコインを購入するといった積立スケジュールを管理できます。
スケジュールに沿って、ご自身の利用されている取引所でビットコインが購入されます。

＜積立開始までの３ステップ＞
STEP1. アプリを開いてログイン

STEP2. APIキー・APIシークレットを登録して取引所と連携

STEP3. 積立スケジュール・金額を設定

詳しくはこちら: https://dca-web.andgo.co.jp/start

※ 購入スケジュールを有効にするためには、取引所毎に適切なAPIキー・APIシークレットの権限設定が必要になります。
設定についてはこちらをご覧ください。https://dca-web.andgo.co.jp/api-register-1

ご不明点等などございましたら、公式サイト内のチャット欄よりお問い合せください。

公式サイト: https://dca-web.andgo.co.jp/
アプリURL: https://dca.andgo.co.jp/

AndGoビットコイン自動積立貯金アプリのご利用をお待ちしております。

AndGoビットコイン自動積立貯金
サポートチーム

**Comment by MyNameIsOka** [comment]
メールアドレスを`AndGoカスタマーサポートtsumitate_cs@andgo.co.jp`にするためproductionのバックエンド再ディプロイしないといけません。
大丈夫ですか？

**Comment by toshihr** [comment]
@MyNameIsOka 
今回の話じゃないです。
今後そうしたい、って話なのでそのタイミングでbackendのデプロイですね。

**Comment by toshihr** [comment]
@AkaneTaguchi-AndGo 
今回の５人は手動で送って下さい
初回ログイン時の自動化は将来の話です。開発にはそれなりの工数かかるので。

**Comment by toshihr** [comment]
リリースおわったようなのでクローズします！

**Comment by toshihr** [comment]
> @MyNameIsOka Hi, Good morning. Could you arrange welcome mail on SendGrid once a user signed up to Hongo App for the first time?
> 
> Sender: AndGoカスタマーサポート[tsumitate_cs@andgo.co.jp](mailto:tsumitate_cs@andgo.co.jp)
> 
> Subject: 【AndGoビットコイン自動積立貯金】はじめかた
> 
> Contents: ようこそ、AndGoビットコイン自動積立貯金アプリへ。 このアプリでは、どの取引所で何時、いくら相当のビットコインを購入するといった積立スケジュールを管理できます。 スケジュールに沿って、ご自身の利用されている取引所でビットコインが購入されます。
> 
> ＜積立開始までの３ステップ＞ STEP1. アプリを開いてログイン
> 
> STEP2. APIキー・APIシークレットを登録して取引所と連携
> 
> STEP3. 積立スケジュール・金額を設定
> 
> 詳しくはこちら: https://dca-web.andgo.co.jp/start
> 
> ※ 購入スケジュールを有効にするためには、取引所毎に適切なAPIキー・APIシークレットの権限設定が必要になります。 設定についてはこちらをご覧ください。https://dca-web.andgo.co.jp/api-register-1
> 
> ご不明点等などございましたら、公式サイト内のチャット欄よりお問い合せください。
> 
> 公式サイト: https://dca-web.andgo.co.jp/ アプリURL: https://dca.andgo.co.jp/
> 
> AndGoビットコイン自動積立貯金アプリのご利用をお待ちしております。
> 
> AndGoビットコイン自動積立貯金 サポートチーム

https://github.com/andgohq/hongo-app/issues/276
こちらのIssueに引き継ぎます
